"""empty message

Revision ID: 221926b59f14
Revises: cb4f609436b3
Create Date: 2020-09-22 23:37:42.864597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '221926b59f14'
down_revision = 'cb4f609436b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('highlight_post', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.drop_column('highlight_post', 'creat_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('highlight_post', sa.Column('creat_time', mysql.DATETIME(), nullable=True))
    op.drop_column('highlight_post', 'create_time')
    # ### end Alembic commands ###
