"""empty message

Revision ID: 450443ecc499
Revises: 0029e1e562d8
Create Date: 2020-09-10 16:11:29.502983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '450443ecc499'
down_revision = '0029e1e562d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('telephone', table_name='front_user')
    op.drop_column('front_user', 'telephone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('telephone', mysql.VARCHAR(length=11), nullable=False))
    op.create_index('telephone', 'front_user', ['telephone'], unique=True)
    # ### end Alembic commands ###
